services:
  postgres:
    image: postgres:16-alpine
    container_name: moyaigra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: moyaigra_user
      POSTGRES_PASSWORD: moyaigra_password
      POSTGRES_DB: moyaigra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moyaigra_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

